os: Visual Studio 2015

platform: x64

environment: 
  BOOST_ROOT: C:\Libraries\boost_1_59_0 
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

build_script: 
  - mkdir build 
  - cd build 
  - cmake -G "Visual Studio 14 2015 Win64" -DUSE_STATIC_BOOST=NO  ..
  - cmake --build . --config Debug

test_script: 
  - ctest -VV -C Debug 